import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowRight, BookOpen, Search, X } from 'lucide-react';
import { apiBaseUrl } from '@/lib/api';
import { clientTestCommands, nodeClientExample, openClawConfig } from '@/lib/integration';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { CopyButton } from '@/components/common/CopyButton';

type GuideSection = { title: string; paragraphs: string[]; code?: string; action?: { label: string; to: string } };
type GuideTopic = { id: string; title: string; summary: string; sections: GuideSection[] };

function guideTopics(base: string): GuideTopic[] {
  return [
    { id: 'start', title: 'Start here', summary: 'Run the router and make your first request.', sections: [
      { title: 'Run your own instance', paragraphs: ['Install Node.js 22.13 or newer. From the project folder, install dependencies and start the API and dashboard. Open the dashboard on localhost port 3001. The API runs on port 3000.'], code: 'npm ci\nnpm run dev' },
      { title: 'Explore without a provider account', paragraphs: ['With no provider keys, the router simulates completions locally. Playground still classifies prompts and ranks models. The request log labels these responses as simulated. This checks the router, not a provider account.'], action: { label: 'Open Playground', to: '/playground' } },
      { title: 'Unlock Settings', paragraphs: ['In another terminal, run the command below from the same project folder. Paste the administrator key into Settings. This key manages the router. Keep it separate from the router keys you give to apps.'], code: 'npm run admin:key', action: { label: 'Open Settings', to: '/settings' } },
      { title: 'Connect a provider, then an app', paragraphs: ['Save a provider key in Settings. Create a router key for your app and copy it once. Use the displayed base URL ending in /v1 and the model alias auto. Run a short prompt and inspect its entry in Requests.'] },
    ] },
    { id: 'providers', title: 'Connect providers', summary: 'Built in adapters, custom APIs, models, and key management.', sections: [
      { title: 'Choose a built in provider', paragraphs: ['Settings supports OpenAI, Anthropic, Google Gemini, OpenRouter, and Groq. Choose Add key, paste the provider key, and save. Provider keys are encrypted on this server and are never returned by the API.', 'Saving does not validate account credit or model access and does not make a paid call. Run a short prompt to verify the account.'], action: { label: 'Manage providers', to: '/settings' } },
      { title: 'Add another compatible API', paragraphs: ['Choose Add custom provider for DeepSeek, Moonshot, or another server using OpenAI Chat Completions with bearer authentication. Enter the provider name, API base URL, key, and exact model ID from its documentation.', 'The router appends /chat/completions to the base URL. Use HTTPS for remote providers. Localhost also accepts HTTP. Native formats such as Azure specific authentication or the Responses API need a dedicated adapter and are not accepted automatically.'] },
      { title: 'Describe the model accurately', paragraphs: ['Enter the current input and output prices in USD per million tokens, plus the context window. The API stores prices per thousand tokens. Enable function tools only when that model supports them.', 'Routing estimates and task strengths affect model selection. The initial quality and latency values are editable estimates, not measured benchmarks. Add coding and other strengths when appropriate. Custom models remain in the catalog after scheduled refreshes.'] },
      { title: 'Replace or remove credentials', paragraphs: ["Use Replace key for a built in provider. Use Edit model and key for a custom provider. A blank key keeps the saved custom key. Changing the base URL requires entering the key again.", 'Remove deletes a saved provider key. Removing a custom provider also removes its catalog models. Request history remains. Environment managed keys must be changed in the server environment and require a restart.'] },
    ] },
    { id: 'apps', title: 'Connect apps', summary: 'OpenClaw, Node.js, router keys, and network addresses.', sections: [
      { title: 'Use a router key', paragraphs: ['Create a named connection in Settings and copy its key once. Give each app a separate router key so you can revoke one connection without changing the others. Router keys can run completions and discover models. They cannot administer Settings or read usage history.', `The base URL for this instance is ${base}/v1. Use auto for balance, auto-cheap for cost, or auto-best for quality.`], action: { label: 'Create a router key', to: '/settings' } },
      { title: 'Configure OpenClaw', paragraphs: ['Merge this configuration into the OpenClaw gateway configuration file, openclaw.json. Set AI_MODEL_ROUTER_KEY in the environment of the gateway process and restart it. A service needs the variable in its service environment.', 'Use openai-completions for this endpoint. Keep any model policy consistent with ai-model-router/auto. To use another alias, update both the primary model reference and the matching model ID in the provider model list. The example context and output limits are starting values. Adjust them to fit your configured models.'], code: openClawConfig(base) },
      { title: 'Call from Node.js', paragraphs: ['Set AI_MODEL_ROUTER_KEY to a generated router key. This example uses the standard fetch function in Node.js and makes one provider request when the router is live.'], code: nodeClientExample(base) },
      { title: 'Use an address the app can reach', paragraphs: ['Localhost refers to the machine or container running the app. A remote OpenClaw gateway cannot reach a router on your laptop through its own localhost. Use a reachable HTTPS address or a private tunnel. Keep the router running while clients use it.'] },
    ] },
    { id: 'testing', title: 'Test a connection', summary: 'JSON, streaming, function tools, request logs, and revocation.', sections: [
      { title: 'Run the client checks', paragraphs: ['Run these commands in PowerShell from the project folder. Enter a generated router key at the hidden prompt. The basic test checks authentication, model discovery, JSON, and SSE streaming. The tools option adds a harmless function call and result round trip.', 'The basic test makes two live requests. The tools command makes four live requests including its basic checks. Provider charges apply. Run from the client machine to also verify its network access.'], code: clientTestCommands(base) },
      { title: 'Know what passed', paragraphs: ['Each successful check reports PASS and relevant request IDs. Find those IDs in Requests and confirm the entries are marked Live. The selected model and usage should agree with the API response.', 'The client test refuses simulated replies by default. Use the command below for a local protocol check only. Simulation does not validate a real provider key, account, or installed client.'], code: 'npm run test:client -- --allow-offline', action: { label: 'Inspect Requests', to: '/requests' } },
      { title: 'Finish in your actual app', paragraphs: ['Send a message from OpenClaw or your own client. Then try a harmless tool task if the app uses tools. Verify both requests in the log. The router forwards tool definitions and results. The client executes tools under its own permissions.', 'SSE replies arrive after the provider completes, with keepalives while waiting. This is buffered streaming. Images, audio, embeddings, provider specific reasoning extensions, and the Responses API are not implemented. Gemini is text only in the compatibility layer.'] },
      { title: 'Verify key revocation', paragraphs: ['Create a disposable router key and confirm the client test accepts it. Revoke that key in Settings and confirm the action. Run the test again with the same key. It must receive HTTP 401.', 'Revocation blocks new requests. It does not cancel requests already in progress. Removing the final router key does not reopen unauthenticated access.'] },
    ] },
    { id: 'dashboard', title: 'Use the dashboard', summary: 'Playground, routing decisions, analytics, filters, and exports.', sections: [
      { title: 'Run or explain a prompt', paragraphs: ['In Playground, enter a prompt or choose an example. Set a routing priority and response speed. Run prompt calls the selected provider and records a request. Explain routing skips the completion and shows candidate scores.', 'With a live OpenAI key, an ambiguous prompt can make a classifier call even during Explain routing. Stop waiting ends the browser wait. It does not cancel a provider request already in progress.'] },
      { title: 'Inspect the result', paragraphs: ['The Decision view shows the selected model, task, difficulty, weights, and candidates. Response contains the answer and execution details. JSON shows the complete result. Copy the response or follow the request link to its saved routing decision.'] },
      { title: 'Read usage and model data', paragraphs: ['Overview and Analytics use the selected UTC date range. Simulated and seeded records are labeled. Costs use reported token counts when available and estimated counts otherwise. Savings compare with a fixed premium baseline, not an alternative invoice.', 'Models supports search, provider filtering, and sorting by name, input price, or quality estimate. Refresh reloads the stored catalog. The server refreshes catalog metadata on its own schedule.'] },
      { title: 'Find and export requests', paragraphs: ['Requests shows the latest 200 records. Filter by model, provider, task, source, or request ID. Use Outcome to view successes or failures. Expand a row for the route and copy its ID. Export JSON downloads the currently filtered records.', 'Prompt and reply bodies are not saved in the request log. Provider keys and full router keys are not part of exports.'] },
    ] },
    { id: 'troubleshooting', title: 'Troubleshooting', summary: 'Connection errors, rejected keys, model access, and failed requests.', sections: [
      { title: 'API unreachable or connection refused', paragraphs: ['Check that the router is running. Confirm its address in Settings. Use port 3000 for the API and port 3001 for the development dashboard. On a remote client, check the hostname, firewall, tunnel, and HTTPS configuration.'] },
      { title: 'HTTP 401, missing or invalid key', paragraphs: ['Use a generated router key in your app, not a provider key. Check whether the router key was revoked or copied incorrectly. Settings requires the administrator key from npm run admin:key.'] },
      { title: 'HTTP 403, forbidden', paragraphs: ['Router keys are restricted to completion endpoints and model discovery. Use the administrator key for dashboard data and Settings. Do not put the administrator key into an app to bypass that separation.'] },
      { title: 'HTTP 422, no capable model', paragraphs: ['Check context size, task strengths, quality estimates, and function tool capability. An agent conversation needs at least one configured model that supports tools. A model may be excluded when the prompt is too large or its capability does not meet the task constraints.'] },
      { title: 'HTTP 502, provider error', paragraphs: ['Check the provider base URL, exact model ID, key permissions, account credit, and current availability. A saved key is not proof that the account can run the selected model. Look up the request ID in Requests and review sanitized server logs.'] },
      { title: 'HTTP 429, rate limited', paragraphs: ['Wait for the rate limit window to reset. The API limit is configured by RATE_LIMIT_MAX and RATE_LIMIT_WINDOW_SEC. Settings requests, and requests that present a key the router does not accept, have their own limit of 60 per minute per address. Avoid repeated retries while a limit is active.'] },
      { title: 'Still in offline mode', paragraphs: ['Add a provider key. If offline mode is forced, remove AI_MODEL_ROUTER_OFFLINE=1 or set it to 0 and restart the API. A provider key cannot override forced offline mode.'] },
      { title: 'Browser cannot save or revoke', paragraphs: ['Restart the API after updating the project. The API must allow PUT and DELETE in browser preflight requests. When the dashboard uses another origin, add that exact origin to CORS_ORIGIN and restart.'] },
    ] },
    { id: 'hosting', title: 'Hosting and license', summary: 'Production setup, backups, privacy, and permitted use.', sections: [
      { title: 'Build and host', paragraphs: ['Use one Node.js process with a persistent disk. The production server serves the dashboard and API together on port 3000. Configure HTTPS for remote use and set HOST to the required bind address.'], code: 'npm ci\nnpm run build\nnpm start' },
      { title: 'Back up keys and request history', paragraphs: ['Stop the API before making a simple file backup. Copy the SQLite database and credentials.key together, or retain the external encryption secret if one is configured. Keep both private. Losing the encryption key makes saved provider credentials unreadable.', 'Provider requests send prompt and tool content to the selected service. The router stores request metadata, not prompt or reply bodies. Review logs and exports before sharing them.'] },
      { title: 'Understand the license', paragraphs: ['The current license is PolyForm Shield 1.0.0. It allows personal use, study, modification, and internal commercial use within its terms. It restricts providing competing products or services, including free competitors. Selling or hosting a competing router requires separate permission.', 'This is source available software rather than OSI open source. The full license controls. Third-party code included under its own MIT terms keeps those permissions, and dependencies keep their own licenses. There is no scheduled conversion to MIT.'] },
    ] },
  ];
}

export function GuidePage() {
  const [params, setParams] = useSearchParams();
  const [query, setQuery] = useState('');
  const selectedTopic = params.get('topic');
  useEffect(() => {
    document.getElementById('main-content')?.scrollTo(0, 0);
  }, [selectedTopic]);
  const topics = guideTopics(apiBaseUrl());
  const needle = query.trim().toLowerCase();
  const matches = topics.filter((topic) => `${topic.title} ${topic.summary} ${topic.sections.map((section) => `${section.title} ${section.paragraphs.join(' ')} ${section.code ?? ''}`).join(' ')}`.toLowerCase().includes(needle));
  const topic = matches.find((item) => item.id === selectedTopic) ?? matches[0];
  return <div className="guide-page">
    <header className="guide-header"><div><p className="eyebrow">Help when you need it</p><h1 className="page-title mt-3">User guide</h1><p className="page-description">From a fresh install to a verified app connection.</p></div><div className="relative w-full sm:max-w-sm"><label htmlFor="guide-search" className="sr-only">Search the user guide</label><Search className="pointer-events-none absolute left-3 top-3.5 h-4 w-4 text-muted-foreground" aria-hidden="true" /><Input id="guide-search" type="search" placeholder="Search keys, OpenClaw, errors" value={query} onChange={(event) => setQuery(event.target.value)} className="pl-10 pr-10" />{query && <Button variant="ghost" size="icon" className="absolute right-0 top-0" aria-label="Clear guide search" onClick={() => setQuery('')}><X aria-hidden="true" /></Button>}</div></header>
    <div className="guide-layout"><nav aria-label="Guide topics" className="guide-topics"><p className="eyebrow mb-3 px-3">{needle ? `${matches.length} matching topics` : 'In this guide'}</p>{matches.map((item) => <button key={item.id} type="button" aria-pressed={topic?.id === item.id} onClick={() => setParams({ topic: item.id })} className="guide-topic"><span>{item.title}</span><ArrowRight className="h-3.5 w-3.5 shrink-0" aria-hidden="true" /></button>)}<Link to="/settings" className="subtle-link mt-5 px-3">Open Settings<ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></nav>
      {topic ? <article key={topic.id} className="guide-article" aria-labelledby="guide-topic-title"><div className="guide-article-heading"><BookOpen className="h-5 w-5 text-primary" aria-hidden="true" /><div><h2 id="guide-topic-title" className="text-2xl font-semibold tracking-tight">{topic.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{topic.summary}</p></div></div>{topic.sections.map((section, index) => <section key={section.title} className="guide-section"><span className="guide-step-number" aria-hidden="true">0{index + 1}</span><div className="min-w-0"><h3 className="text-base font-semibold tracking-tight">{section.title}</h3>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mt-3 text-sm leading-7 text-muted-foreground">{paragraph}</p>)}{section.code && <div className="mt-4 min-w-0"><div className="mb-2 flex justify-end"><CopyButton text={section.code} label="Copy code" description={`Copy ${section.title} code`} /></div><pre className="code-surface max-h-96">{section.code}</pre></div>}{section.action && <Link className="subtle-link mt-3" to={section.action.to}>{section.action.label}<ArrowRight className="h-4 w-4" aria-hidden="true" /></Link>}</div></section>)}</article> : <div className="py-12" role="status"><h2 className="text-xl font-semibold">No guide topics match.</h2><p className="mt-3 text-sm text-muted-foreground">Try provider, key, OpenClaw, or an HTTP status code.</p><Button variant="outline" className="mt-5" onClick={() => setQuery('')}>Show all topics</Button></div>}
    </div>
  </div>;
}
